# Use the official OpenJDK base image with Maven
FROM maven:latest

# Install Git
# RUN apt-get update && apt-get install -y git

# Set the working directory inside the container
# WORKDIR /workspace

# Set up Java environment variables
# ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
# ENV PATH=$JAVA_HOME/bin:$PATH

# Expose the port used by Quarkus
# EXPOSE 8080

# Set the default command to run Quarkus in dev mode
# CMD ["mvn", "quarkus:dev"]